### ISSUE TITLE
GIF java.lang.ArrayIndexOutOfBoundsException: 4096

### ISSUE THREAD

**Issue by snaquekiller** [coobird/thumbnailator#120]
## Expected behavior
_Please describe what you are expecting the library to perform._
create thumbnail

## Actual behavior
_Please describe the actual behavior you are experiencing, including stack
trace and other information which would help diagnose the issue._

```
 java.lang.ArrayIndexOutOfBoundsException: 4096
 	at com.sun.imageio.plugins.gif.GIFImageReader.read(GIFImageReader.java:984)
at net.coobird.thumbnailator.tasks.io.FileImageSource.read(Unknown Source)
	at net.coobird.thumbnailator.tasks.SourceSinkThumbnailTask.read(Unknown Source)
at net.coobird.thumbnailator.Thumbnailator.createThumbnail(Unknown Source)
	at net.coobird.thumbnailator.Thumbnails$Builder.toOutputStream(Unknown Source)
```

## Steps to reproduce the behavior
_Please enter step-by-step instructions for reproducing the actual behavior.
Including code can be helpful in diagnosing issue, but please keep the code to
a minimal that will reproduce the behavior._
![200_002](https://user-images.githubusercontent.com/9265270/27187647-0863a342-51ec-11e7-91b0-424717d4242c.gif)
![10](https://user-images.githubusercontent.com/9265270/27187655-0c2bcb76-51ec-11e7-81c3-22041912e1b1.gif)
try to create thumbnail of this two gif

## Environment
_Please provide vendor and version information for the Operating System,
JDK, and Thumbnailator. Please feel free to add any other information
which may be pertinent._

- OS vendor and version: linux
- JDK vendor and version:1.8
- Thumbnailator version: 0.4.8

**Comment by coobird** [comment]
@snaquekiller,  sorry for the late reply.

I'd like to get clarification on your issue -- what are your expectations? You'll need to be more clear about what you expect.

I'm going to guess that you want to resize an animated GIF?

**Comment by gssitrainee** [comment]
*Same problem here*

- OS vendor and version: Windows 10
- JDK vendor and version:1.8
- Thumbnailator version: 0.4.8

**Comment by freehuoshan** [comment]
sample problem

java.lang.ArrayIndexOutOfBoundsException: 4096
	at com.sun.imageio.plugins.gif.GIFImageReader.read(GIFImageReader.java:984) ~[na:1.8.0_60]
	at net.coobird.thumbnailator.tasks.io.InputStreamImageSource.read(Unknown Source) ~[thumbnailator-0.4.8.jar!/:0.4.8]
	at net.coobird.thumbnailator.tasks.SourceSinkThumbnailTask.read(Unknown Source) ~[thumbnailator-0.4.8.jar!/:0.4.8]
	at net.coobird.thumbnailator.Thumbnailator.createThumbnail(Unknown Source) ~[thumbnailator-0.4.8.jar!/:0.4.8]
	at net.coobird.thumbnailator.Thumbnails$Builder.toOutputStream(Unknown Source) ~[thumbnailator-0.4.8.jar!/:0.4.8]
	at com.github.tobato.fastdfs.service.DefaultFastFileStorageClient.getThumbImageStream(DefaultFastFileStorageClient.java:185) ~[fastdfs-client-1.25.4-RELEASE.jar!/:1.25.4-RELEASE]
	at com.github.tobato.fastdfs.service.DefaultFastFileStorageClient.uploadThumbImage(DefaultFastFileStorageClient.java:154) ~[fastdfs-client-1.25.4-RELEASE.jar!/:1.25.4-RELEASE]

- OS Ubuntu 16.04
- JDK 1.8
- Thumbnailator 0.4.8

**Comment by freehuoshan** [comment]
https://github.com/DhyanB/Open-Imaging

I found a solution here, please solve this bug in the new version.

**Comment by coobird** [comment]
@freehuoshan , thank you for adding more information about this issue.

So this is an issue that the GIF decoder bundled with the JRE, and can be found discussed here:
https://stackoverflow.com/questions/22259714/arrayindexoutofboundsexception-4096-while-reading-gif-file

Since Thumbnailator relies on the image readers and writers provided by Java Image I/O, providing bug fixes for those are out of scope of this project. I'm going to close this, as it's not a problem with Thumbnailator itself.
