### ISSUE TITLE
java.lang.IllegalStateException: scale is not set. 

### ISSUE THREAD

**Issue by BlackJia** [coobird/thumbnailator#133]
at net.coobird.thumbnailator.Thumbnails$Builder.checkReadiness(Unknown Source) 	
at net.coobird.thumbnailator.Thumbnails$Builder.asBufferedImage(Unknown Source)

how can i fix it.

**Comment by BlackJia** [comment]
sorry I miss some set
Thumbnails.of(file.getInputStream()).scale(1.0f)
