### ISSUE TITLE
No suitable ImageReader found for C:\Users\LKhore\Pictures\Screenshots\desktop.ini

### ISSUE THREAD

**Issue by lkhore** [coobird/thumbnailator#146]
## Expected behavior
_Please describe what you are expecting the library to perform._

## Actual behavior
_Please describe the actual behavior you are experiencing, including stack
trace and other information which would help diagnose the issue._

net.coobird.thumbnailator.tasks.UnsupportedFormatException: No suitable ImageReader found for C:\Users\LKhore\Pictures\Screenshots\desktop.ini.
	at net.coobird.thumbnailator.tasks.io.FileImageSource.read(Unknown Source)
	at net.coobird.thumbnailator.tasks.SourceSinkThumbnailTask.read(Unknown Source)
	at net.coobird.thumbnailator.Thumbnailator.createThumbnail(Unknown Source)
	at net.coobird.thumbnailator.Thumbnails$Builder.asFiles(Unknown Source)Disconnected from the target VM, address: '127.0.0.1:50696', transport: 'socket'

	at net.coobird.thumbnailator.Thumbnails$Builder.toFiles(Unknown Source)
	at net.coobird.thumbnailator.Thumbnails$Builder.toFiles(Unknown Source)
	at Thumb.main(Thumb.java:13)

## Steps to reproduce the behavior
_Please enter step-by-step instructions for reproducing the actual behavior.
Including code can be helpful in diagnosing issue, but please keep the code to
a minimal that will reproduce the behavior._

## Environment
_Please provide vendor and version information for the Operating System,
JDK, and Thumbnailator. Please feel free to add any other information
which may be pertinent._

- OS vendor and version:
Windows
- JDK vendor and version:
1.8
- Thumbnailator version:
[0.4, 0.5)

**Comment by thanossv** [comment]
From what I see, the program attempted to process the hidden windows file "desktop.ini", but, since it's not an image, it failed.
Try to exclude this file from processing to see if this resolves your issue.

Cheers,
Thanos

**Comment by coobird** [comment]
As @thanossv, it appears to be an issue with attempting to read `desktop.ini` which is not an image.
