### ISSUE TITLE
How to convert from CMYK to RGB

### ISSUE THREAD

**Issue by GoogleCodeExporter** [coobird/thumbnailator#35]
```
I need convert img from CMYK to RGB?

How to convert from CMYK to RGB?

Please...:)

```

Original issue reported on code.google.com by `thomasta...@gmail.com` on 18 Apr 2012 at 8:47

**Comment by ijxdb** [comment]
I am using Thumbnailator lib to create thumbnails. But it fails to create thumbnail for cmyk images.

at com.sun.imageio.plugins.jpeg.JPEGImageReader.readInternal(JPEGImageReader.java:1068)

	at com.sun.imageio.plugins.jpeg.JPEGImageReader.read(JPEGImageReader.java:1039)

	at net.coobird.thumbnailator.tasks.io.InputStreamImageSource.read(Unknown Source)

	at net.coobird.thumbnailator.tasks.SourceSinkThumbnailTask.read(Unknown Source)

	at net.coobird.thumbnailator.Thumbnailator.createThumbnail(Unknown Source)

	at net.coobird.thumbnailator.Thumbnails$Builder.toOutputStream(Unknown Source)

	at net.coobird.thumbnailator.Thumbnailator.createThumbnail(Unknown Source)

	at net.coobird.thumbnailator.Thumbnailator.createThumbnail(Unknown Source)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.lang.reflect.Method.invoke(Method.java:498)


javax.imageio.IIOException: javax.imageio.IIOException: Unsupported Image Type

Please can you suggest any work arounds?
