### ISSUE TITLE
Exception thrown when attempting to resize a CMYK JPEG

### ISSUE THREAD

**Issue by GoogleCodeExporter** [coobird/thumbnailator#48]
```
What steps will reproduce the problem?
1.Thumbnails.of(new 
File("/Users/wq/Downloads/covecfe6c5888b1e.JPG")).size(100,100).toFile(new 
File("/Users/wq/Downloads/abc.jpg"));
2.
3.

What is the expected output? What do you see instead?


What version of the product are you using? On what operating system? Which
version of Java (Sun/Oracle? OpenJDK?) ?
MacOSX,oracle-jdk7.


Please provide any additional information below.
javax.imageio.IIOException: Improper call to JPEG library in state 202
    at com.sun.imageio.plugins.jpeg.JPEGImageReader.readImageHeader(Native Method)
    at com.sun.imageio.plugins.jpeg.JPEGImageReader.readNativeHeader(JPEGImageReader.java:550)
    at com.sun.imageio.plugins.jpeg.JPEGImageReader.checkTablesOnly(JPEGImageReader.java:295)
    at com.sun.imageio.plugins.jpeg.JPEGImageReader.gotoImage(JPEGImageReader.java:427)
    at com.sun.imageio.plugins.jpeg.JPEGImageReader.readHeader(JPEGImageReader.java:543)
    at com.sun.imageio.plugins.jpeg.JPEGImageReader.readInternal(JPEGImageReader.java:986)
    at com.sun.imageio.plugins.jpeg.JPEGImageReader.read(JPEGImageReader.java:966)
    at javax.imageio.ImageReader.read(ImageReader.java:940)
    at net.coobird.thumbnailator.tasks.io.FileImageSource.read(Unknown Source)
    at net.coobird.thumbnailator.tasks.SourceSinkThumbnailTask.read(Unknown Source)
    at net.coobird.thumbnailator.Thumbnailator.createThumbnail(Unknown Source)
    at net.coobird.thumbnailator.Thumbnails$Builder.toFile(Unknown Source)
```

Original issue reported on code.google.com by `clay...@gmail.com` on 26 Jun 2013 at 8:19

**Comment by BedunkevichE** [comment]
Hi, have the same problem.

javax.imageio.IIOException: Unsupported Image Type
    at com.sun.imageio.plugins.jpeg.JPEGImageReader.readInternal(JPEGImageReader.java:1068)
    at com.sun.imageio.plugins.jpeg.JPEGImageReader.read(JPEGImageReader.java:1039)
    at net.coobird.thumbnailator.tasks.io.FileImageSource.read(Unknown Source)
    at net.coobird.thumbnailator.tasks.SourceSinkThumbnailTask.read(Unknown Source)
    at net.coobird.thumbnailator.Thumbnailator.createThumbnail(Unknown Source)

when try to resize СMYK image
the target image is attached.

![channel_digital_image_cmyk_color](https://cloud.githubusercontent.com/assets/18334690/17963951/6ee95fc6-6ac0-11e6-92b0-096d3f9c12a4.jpg)
