### ISSUE TITLE
OutOfMemoryError: Java heap space / Builder.asBufferedImage

### ISSUE THREAD

**Issue by GoogleCodeExporter** [coobird/thumbnailator#62]
```
What steps will reproduce the problem?
Load 20 differents images (not necessarily large ones).

What is the expected output? What do you see instead?
BufferedImage thumbnail = Thumbnails.of(image).size(Integer.parseInt(width), 
Integer.parseInt(height)).scalingMode(scalingMode).outputQuality(quality).asBuff
eredImage();

Exception in thread "http-bio-8280-exec-9" java.lang.OutOfMemoryError: Java 
heap space
    at java.awt.image.DataBufferByte.<init>(DataBufferByte.java:42)
    at java.awt.image.Raster.createInterleavedRaster(Raster.java:248)
    at java.awt.image.BufferedImage.<init>(BufferedImage.java:370)
    at net.coobird.thumbnailator.resizers.ProgressiveBilinearResizer.resize(Unknown Source)
    at net.coobird.thumbnailator.makers.ThumbnailMaker.makeThumbnail(Unknown Source)
    at net.coobird.thumbnailator.makers.FixedSizeThumbnailMaker.make(Unknown Source)
    at net.coobird.thumbnailator.Thumbnailator.createThumbnail(Unknown Source)
    at net.coobird.thumbnailator.Thumbnails$Builder.asBufferedImage(Unknown Source)

What version of the product are you using? On what operating system? Which
version of Java (Sun/Oracle? OpenJDK?) ?
java version "1.6.0_51"
Java(TM) SE Runtime Environment (build 1.6.0_51-b11-457)
Java HotSpot(TM) 64-Bit Server VM (build 20.51-b01-457, mixed mode)

thumbnailator-0.4.6

Eclipse.ini
-Xmn512m
-Xms1024m
-Xmx2048m
-Xss4m

Please provide any additional information below.
Issue 44 and 46 are kinda the same problem.
```

Original issue reported on code.google.com by `lucasbme...@gmail.com` on 2 Dec 2013 at 5:06

**Comment by coobird** [comment]
`OutOfMemoryError`s are not necessarily an issue with Thumbnailator itself. JVM heap settings are outside the control of Thumbnailator, so the best it can do is to attempt to reduce memory consumption, such as what #1 aims to do.
