### ISSUE TITLE
"Image cannot be null" when using `Thumbnails.of(BufferedImage...)`

### ISSUE THREAD

**Issue by GoogleCodeExporter** [coobird/thumbnailator#73]
```
What steps will reproduce the problem?

The code is quite simple 


    static public void makeThumbnail(InputStream is, OutputStream os, int width, int height) throws IOException {
        BufferedImage originalImage = ImageIO.read(is);
        Thumbnails.of(originalImage)
                .width(width)
                .height(height)
                .outputFormat("jpg")
                .toOutputStream(os);
    }



    @Test
    public void testGenThumb() throws IOException, InterruptedException {
        File f = new File("testdata/image_1.8m.jpg");
        Assert.assertTrue(f.exists());
        FileInputStream is = new FileInputStream(f);
        for (int i = 0; i < 1000; i++) {
            File out = File.createTempFile("aabb", ".jpg");
            out.deleteOnExit();
            FileOutputStream os = new FileOutputStream(out);
            ImageProcessor.makeThumbnail(is, os, 1000, 1000);
            os.close();
        }
    }
}


When the test running, an exception was raise:
java.lang.NullPointerException: Image cannot be null.
    at net.coobird.thumbnailator.tasks.io.BufferedImageSource.<init>(Unknown Source)
    at net.coobird.thumbnailator.Thumbnails$Builder$BufferedImageImageSourceIterator$1.next(Unknown Source)
    at net.coobird.thumbnailator.Thumbnails$Builder$BufferedImageImageSourceIterator$1.next(Unknown Source)
    at net.coobird.thumbnailator.Thumbnails$Builder.toOutputStream(Unknown Source)
    at com.xiaomi.mfs.ImageProcessor.makeThumbnail(ImageProcessor.java:30)
    at com.xiaomi.mfs.test.ImageTest.testGenThumb(ImageTest.java:27)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:74)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:211)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:67)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)


If the file open failed, it should failed at
Assert.assertTrue(f.exists());


What version of the product are you using? On what operating system? Which
version of Java (Sun/Oracle? OpenJDK?) ?

java version "1.8.0_05"
Java(TM) SE Runtime Environment (build 1.8.0_05-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.5-b02, mixed mode)


Please provide any additional information below.


```

Original issue reported on code.google.com by `pcman.zh...@gmail.com` on 23 Dec 2014 at 2:25

**Comment by sundayha** [comment]
Jdk 1.8 has the same error, jdk 10 does not have this error
