### ISSUE TITLE
Asynchronous IO over SSH file system - no suitable ImageReader found

### ISSUE THREAD

**Issue by sarnobat** [coobird/thumbnailator#81]
With a plain java.nio local file system, I'm able to create a thumbnail using streamed input and output. It also works when I use Apache Mina SSHD stream (synchronous I/O) on that same file. However, this image doesn't work when I stream in from com.pastdev.jsch.nio.file.UnixSshFileSystem (https://github.com/lucastheisen/jsch-nio/blob/master/src/main/java/com/pastdev/jsch/nio/file/UnixSshFileSystem.java) I get the following exception (for all my iPhone photographs, but some web images work fine - maybe it is size related?) . I doubt it's a problem in your library, but can you help me figure out what the shortcoming is in the JSCH-NIO file system?

```
net.coobird.thumbnailator.tasks.UnsupportedFormatException: No suitable ImageReader found for source data.
        at net.coobird.thumbnailator.tasks.io.InputStreamImageSource.read(Unknown Source)
        at net.coobird.thumbnailator.tasks.SourceSinkThumbnailTask.read(Unknown Source)
        at net.coobird.thumbnailator.Thumbnailator.createThumbnail(Unknown Source)
        at net.coobird.thumbnailator.Thumbnails$Builder.toOutputStream(Unknown Source)
        at net.coobird.thumbnailator.Thumbnailator.createThumbnail(Unknown Source)
        at net.coobird.thumbnailator.Thumbnailator.createThumbnail(Unknown Source)
        at net.coobird.thumbnailator.Thumbnailator$createThumbnail$1.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:128)
        at Coagulate$MyResource$2.write(server.groovy:206)
        at org.glassfish.jersey.message.internal.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:76)
        at org.glassfish.jersey.message.internal.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:58)
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.aroundWriteTo(WriterInterceptorExecutor.java:194)
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:139)
        at org.glassfish.jersey.server.internal.JsonWithPaddingInterceptor.aroundWriteTo(JsonWithPaddingInterceptor.java:103)
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:139)
        at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundWriteTo(MappableExceptionWrapperInterceptor.java:88)
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:139)
        at org.glassfish.jersey.message.internal.MessageBodyFactory.writeTo(MessageBodyFactory.java:1005)
        at org.glassfish.jersey.server.ServerRuntime$Responder.writeResponse(ServerRuntime.java:471)
        at org.glassfish.jersey.server.ServerRuntime$Responder.processResponse(ServerRuntime.java:333)
        at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:323)
        at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:227)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:198)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:946)
        at org.glassfish.jersey.jdkhttp.JdkHttpHandlerContainer.handle(JdkHttpHandlerContainer.java:164)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
        at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:80)
        at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:677)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
        at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:649)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
```

I'll give you a test case in my next comment.

**Comment by sarnobat** [comment]
``` java
import java.io.IOException;
import java.io.InputStream;
import java.net.URI;
import java.net.URISyntaxException;
import java.nio.file.FileSystem;
import java.nio.file.FileSystems;
import java.nio.file.Path;
import java.nio.file.spi.FileSystemProvider;
import java.util.HashMap;
import java.util.Map;

import org.json.JSONException;

import com.pastdev.jsch.DefaultSessionFactory;

public class Test {
    public static void main(String[] args) throws URISyntaxException, JSONException, IOException {
        Path path = getAsyncClient().getPath("/iPhone pics/2015-04-28 031.jpg");
        FileSystemProvider provider = path.getFileSystem().provider();
        final InputStream is = provider.newInputStream(path);
        net.coobird.thumbnailator.Thumbnailator.createThumbnail(is, System.out, 100, 100);
    }

    private static FileSystem getAsyncClient() {
        DefaultSessionFactory defaultSessionFactory;
        try {
            defaultSessionFactory = new DefaultSessionFactory("myusername", "192.168.1.2", 22);
        } catch (Exception e) {
            e.printStackTrace();
            throw new RuntimeException(e);
        }
        try {
            defaultSessionFactory.setKnownHosts(System.getProperty("user.home")
                    + "/.ssh/known_hosts");
            defaultSessionFactory.setIdentityFromPrivateKey(System.getProperty("user.home")
                    + "/.ssh/id_rsa");
        } catch (Exception e) {
            e.printStackTrace();
            System.exit(-1);
        }
        Map<String, Object> environment = new HashMap<String, Object>();
        environment.put("defaultSessionFactory", defaultSessionFactory);
        URI uri;
        try {
            uri = new URI("ssh.unix://myusername@192.168.1.2:22/home/myusername");
        } catch (URISyntaxException e) {
            throw new RuntimeException(e);
        }
        FileSystem sshfs;
        try {
            sshfs = FileSystems.newFileSystem(uri, environment, Test.class.getClassLoader());
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
        return sshfs;
    }
}
```

```

        <dependency>
            <groupId>com.pastdev</groupId>
            <artifactId>jsch-nio</artifactId>
            <version>0.1.5</version>
        </dependency> 
        <dependency>
            <groupId>net.coobird</groupId>
            <artifactId>thumbnailator</artifactId>
            <version>0.4.8</version>
        </dependency>
```

**Comment by coobird** [comment]
Without looking into the specifics of the jsch-nio library and its behavior, here are my thoughts:

The "No suitable ImageReader found for source data." message is given when the underlying Java Image I/O API cannot find a suitable `ImageReader` for a given data stream. It is my understanding that the Image I/O API will determine the appropriate format by examining the data stream for hints such as image file headers and such. (The `ImageReader`s will register themselves with the Image I/O API so that the API can support multiple images formats in a plug-in type architecture.)

So, one possibility is that the image you're trying to read is indeed an unsupported type. However, this is unlikely as the code you provided is referring to a JPEG file.

Another possibility is that the JPEG file itself may be corrupted. To check this, try opening the target file using another image viewer.

One more thing to check is whether the `InputStream` is really actually streaming the contents of the JPEG file correctly... Try to see if you can stream the data from the `InputStream` to a file and see whether the stream is giving a valid JPEG file.

The reason I mention this is because I'm not exactly sure how `jsch-nio` will react when it is given a file that cannot be found or read. Since the file name you specified contains spaces, depending on the behavior of `jsch-nio`, I kind of suspect that it may be returning a "file not found" event through the `InputStream` -- just a wild guess, but the odd behavior you mentioned (sometimes works and sometimes doesn't) indicates to me that maybe the stream is not actually streaming image data.

**Comment by sarnobat** [comment]
Thanks for the analysis. I don't think the file itself is the problem since when I open that file as a local path or ssh synchronous it opens correctly, only via ssh nio it fails .

Since I may not get around to further debugging immediately, feel free to close this ticket. I'll reopen it if I have better proof that there is an issue in `Thumbnailator` rather than `jsch-nio`.

**Comment by Sohnny0** [comment]
WebP images will report this error
