### ISSUE TITLE
Support for Google AppEngine

### ISSUE THREAD

**Issue by dincek** [coobird/thumbnailator#84]
Hi,

I tried to use JPEG resize on Google AppEngine but it is not possible, I got error for using restricted class in java.awt.*. Would it be possible to make changes to library so that it would work on Google AppEngine platform?

Error stack:
java.lang.NoClassDefFoundError: java.awt.RenderingHints is a restricted class. Please see the Google  App Engine developer's guide for more details.
    at com.google.appengine.tools.development.agent.runtime.Runtime.reject(Runtime.java:51)
    at net.coobird.thumbnailator.resizers.configurations.AlphaInterpolation.<clinit>(Unknown Source)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:191)
    at com.google.appengine.tools.development.agent.runtime.RuntimeHelper.checkRestricted(RuntimeHelper.java:70)
    at com.google.appengine.tools.development.agent.runtime.Runtime.checkRestricted(Runtime.java:64)
    at net.coobird.thumbnailator.Thumbnails$Builder.<init>(Unknown Source)
    at net.coobird.thumbnailator.Thumbnails$Builder.ofInputStreams(Unknown Source)
    at net.coobird.thumbnailator.Thumbnails$Builder.access$300(Unknown Source)
    at net.coobird.thumbnailator.Thumbnails.of(Unknown Source)

**Comment by coobird** [comment]
Sorry for the late response.

> Would it be possible to make changes to library so that it would work on Google AppEngine platform?

Unfortunately, the answer is no, because Thumbnailator is a library that depends on classes in the `java.awt` package that the Google App Engine's Java runtime does not provide.
